### ISSUE TITLE
http://xss.localhost/install/step3.php  500 Internal Server Error

### ISSUE THREAD

**Issue by LCconanx** [78778443/xssplatform#10]
http://xss.localhost/install/step3.php， 第三步 500  Internal Server Error

**Comment by KpLi0rn** [comment]
我也是这个问题 同求

**Comment by 78778443** [comment]
方便的话说一下PHP版本 系统等信息。

**Comment by KpLi0rn** [comment]
> 方便的话说一下PHP版本 系统等信息。

您好，我是在docker中进行尝试xss平台的搭建的 
docker环境地址如下：https://hub.docker.com/r/2233466866/lnmp/dockerfile
php版本是：php-7.3.14
nginx版本是：nginx-1.17.8
mysql版本应该是 5.7

**Comment by KpLi0rn** [comment]
> 方便的话说一下PHP版本 系统等信息。

这个docker镜像是基于centos：7的官方镜像

**Comment by 78778443** [comment]
稍等，我给你一个docker版本~

**Comment by KpLi0rn** [comment]
> 稍等，我给你一个docker版本~

非常感谢大师傅！！！谢谢您

**Comment by 78778443** [comment]
docker安装方法：https://segmentfault.com/a/1190000021899373

**Comment by KpLi0rn** [comment]
> docker安装方法：https://segmentfault.com/a/1190000021899373

感谢 我先去就去按照文章来试试

**Comment by LCconanx** [comment]
多谢大神，还是有个问题，我在本地docker搭建和访问成功了，本地绑hosts 127.0.0.1 xss.localhost没问题，但是我在云主机上安装，然后用公网IP远程访问，因为docker里有permeate，用IP没法访问xssplatform，本地绑hosts，公网IP xss.localhost, 也依然访问不了

**Comment by 78778443** [comment]
我建议你登入公网的服务器，在容器里面修改nginx的配置





发自我的iPhone


------------------ Original ------------------
