### ISSUE TITLE
我搭建完之后根本没法用 怎么回事

### ISSUE THREAD

**Issue by naofu** [78778443/xssplatform#11]
搭建好之后平台页面都显示了 但里面的攻击代码只是个get请求，没有js执行。无法达到xss效果。。。。。。。。。

**Comment by 78778443** [comment]
你看看有JS报错没，推荐用docker方式搭建~

https://segmentfault.com/a/1190000021899373

**Comment by naofu** [comment]
> o

谢谢大佬 我用docker试试

**Comment by naofu** [comment]
试了下 按照你的操作安装完没有问题 但就是js无法执行 相当于这平台搭建了没啥作用  攻击代码都有问题
