### ISSUE TITLE
没看见xssplatform

### ISSUE THREAD

**Issue by notwhy** [78778443/xssplatform#12]
看了docker教程
Permeate 轻松渗透测试系统 v1.0
认真观看你的教程 我成功安装 Permeate 轻松渗透测试系统 v1.0
至于xssplatform倒是没看见。。。

**Comment by 78778443** [comment]
你是不是没加 &nbsp;xss.localhost &nbsp;?



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whynot <notifications@github.com&gt;
发送时间: 2020年3月6日 12:57
收件人: 78778443/xssplatform <xssplatform@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[78778443/xssplatform] 没看见xssplatform (#12)

**Comment by notwhy** [comment]
docker里面外面都加了

**Comment by 78778443** [comment]
你访问的域名是多少？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whynot <notifications@github.com&gt;
发送时间: 2020年3月6日 13:06
收件人: 78778443/xssplatform <xssplatform@noreply.github.com&gt;
抄送: daxia <78778443@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[78778443/xssplatform] 没看见xssplatform (#12)

**Comment by notwhy** [comment]
http://x.2w1.pw/

**Comment by 78778443** [comment]
那必然不对啊，我设置的域名是xss.localhost。 &nbsp; 你可以去容器里把nginx配置文件域名改成你自己的啊，不然肯定访问成默认的了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whynot <notifications@github.com&gt;
发送时间: 2020年3月6日 13:13
收件人: 78778443/xssplatform <xssplatform@noreply.github.com&gt;
抄送: daxia <78778443@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[78778443/xssplatform] 没看见xssplatform (#12)




http://x.2w1.pw/

**Comment by notwhy** [comment]
搭建好了 但是xss没有内容啊 http://x.2w1.pw/Q7yYOv?1583472619

**Comment by 78778443** [comment]
我查下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whynot <notifications@github.com&gt;
发送时间: 2020年3月6日 13:31
收件人: 78778443/xssplatform <xssplatform@noreply.github.com&gt;
抄送: daxia <78778443@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[78778443/xssplatform] 没看见xssplatform (#12)




搭建好了 但是xss没有内容啊 http://x.2w1.pw/Q7yYOv?1583472619

**Comment by notwhy** [comment]
已搭建好
