### ISSUE TITLE
使用docker安装，感觉安装的不是XSS平台

### ISSUE THREAD

**Issue by MrPointSun** [78778443/xssplatform#17]
由于是公网ip就没有绑定xss.localhost域名，结果安装的是这玩意儿。。。
![TIM图片20200806123055](https://user-images.githubusercontent.com/49204214/89490995-cf5f5900-d7e0-11ea-9681-d048f48df0fc.png)

请问XSS平台在哪呢。。。

**Comment by MrPointSun** [comment]
我知道docker是默认访问permeate系统了，请问可以改默认访问访问的系统吗？

**Comment by 78778443** [comment]
注意看安装说明，上面有说啊，，

**Comment by Coderzgh** [comment]
浪费时间 这样公网服务器就完全没办法部署了吧？这不是欺骗感情嘛

**Comment by moMaxX** [comment]
> 注意看安装说明，上面有说啊，

师傅，请问按照安装说明安装了，但是xss.localhost还是访问不了，不会要公网Ip去绑定域名吧？
