### ISSUE TITLE
点击查看代码会504

### ISSUE THREAD

**Issue by blackw4tch** [78778443/xssplatform#21]
![image](https://user-images.githubusercontent.com/55129687/97103270-62c07000-16e6-11eb-9b88-3780ede646b6.png)

**Comment by Bronya-Rayi** [comment]
短网址的问题，修改掉source/project.php的第233行即可
![image](https://user-images.githubusercontent.com/47048823/118281401-bd44e080-b4ff-11eb-80be-02dc492a6405.png)
