### ISSUE TITLE
搭建完就是个论坛靶场

### ISSUE THREAD

**Issue by dd404x** [78778443/xssplatform#22]
![image](https://user-images.githubusercontent.com/19923974/105125920-842fcd00-5b18-11eb-8f80-f459a83389c1.png)

**Comment by 78778443** [comment]
注意看安装文档，host不对，你可以去修改容器里面的nginx配置代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "78778443/xssplatform"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 中午12:11
收件人:&nbsp;"78778443/xssplatform"<xssplatform@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[78778443/xssplatform] 搭建完就是个论坛靶场 (#22)

**Comment by dd404x** [comment]
我参考这边文章搭建的 https://segmentfault.com/a/1190000021899373  文章里面容器是不是不对

**Comment by dd404x** [comment]
知道了，谢谢师傅
