### ISSUE TITLE
可以出个docker吗？

### ISSUE THREAD

**Issue by maybe-why-not** [78778443/xssplatform#7]
或者搭建在linux服务器上、没有域名的，虚拟主机、重写路由要在哪里配？一个下午过去了，要是直接访问文件夹就ok该多好。

**Comment by 78778443** [comment]
其实我写了一个，没有公布出来..  你可以把这个里面的文章操作一遍，然后在宿主机中域名 xss.localhost指向127.0.0.1 就可以访问~

**Comment by 78778443** [comment]
https://segmentfault.com/a/1190000017151621

**Comment by maybe-why-not** [comment]
![image](https://user-images.githubusercontent.com/29968903/71322354-add78880-2501-11ea-8a53-714af518b113.png)
