### ISSUE TITLE
我可以在哪里修改CDN请求。

### ISSUE THREAD

**Issue by EternalChampion61** [78778443/xssplatform#8]
我在我的网站成功部署了您的xss平台，但是每次访问时都会有一个指向[https://www.bootstrapcdn.com/bootstrap/2.3.1/js/bootstrap.min.js]的请求，返回结果为404。

我可以在那个文件中修改这个请求？

**Comment by EternalChampion61** [comment]
这个错误影响网站页面加载速度。

**Comment by 78778443** [comment]
已经换成本地文件，已修复
